=== codemonstur/site-plants-cause-disease/src/main/resources/schema/disease.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "visible": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "uri": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "filteredAnecdotes": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "carnivoreDietSearchQueries": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "anecdotes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "visible": {
            "type": "boolean"
          },
          "uri": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        }
      }
    },
    "definition": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "source": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "required": [
        "source",
        "text"
      ]
    },
    "see": {
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "uri",
        "name"
      ]
    },
    "papers": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "articles": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "videos": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "visible",
    "name",
    "uri"
  ]
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/osteopenia.json
{
  "visible": true,
  "name": "Osteopenia",
  "uri": "osteopenia",
  "carnivoreDietSearchQueries": [
    "Osteopenia"
  ],
  "filteredAnecdotes": [],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/mimi-improved-rheumatoid-arthritis-parkinsons-disease-and-osteopenia-on-the-carnivore-diet/",
      "title": "Mimi improved rheumatoid arthritis, Parkinson&#039;s disease, and osteopenia on the carnivore diet",
      "date": "March 7, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/nanci-heals-osteopenia-carnivore-diet/",
      "title": "Nanci heals from osteopenia on the carnivore diet",
      "date": "July 20, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cindy-gets-off-blood-pressure-medication-on-carnivore-diet/",
      "title": "Cindy Gets Off Blood Pressure Medication With the Carnivore Diet",
      "date": "May 6, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/stephen-improved-cancer-diagnosis-carnivore-diet/",
      "title": "Stephen improved his cancer diagnosis with a carnivore diet.",
      "date": "November 1, 2018"
    }
  ],
  "definition": {
    "source": "https://my.clevelandclinic.org/health/diseases/21855-osteopenia",
    "text": "Osteopenia is a loss of bone density. Having reduced bone density means your bones don\u2019t have as much mineral content as they should. This can make them weaker and increase your risk of bone fractures (broken bones). If you have osteopenia, your bone density is lower than average. It can progress to osteoporosis."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/osteoporosis.json
{
  "visible": true,
  "name": "Osteoporosis",
  "uri": "osteoporosis",
  "carnivoreDietSearchQueries": [
    "Osteoporosis"
  ],
  "filteredAnecdotes": [],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/daniel-heals-from-type-2-diabetes-osteoporosis-and-cardiovascular-disease-on-a-carnivore-diet/",
      "title": "Daniel heals from type 2 diabetes, osteoporosis, and cardiovascular disease on a carnivore diet",
      "date": "June 27, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/claire-reverses-osteoporosis-puts-on-muscle-carnivore/",
      "title": "Claire Reverses Osteoporosis and Puts On Muscle In Her 60s On A Carnivore Diet",
      "date": "August 21, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/maria-healed-eating-disorder-gastroparesis-osteoporosis-and-arthritis-on-carnivore-diet/",
      "title": "Maria healed eating disorder, gastroparesis, osteoporosis, and arthritis on carnivore diet",
      "date": "October 22, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jake-improves-athletic-performance-and-mental-clarity-carnivore-diet/",
      "title": "Jake improves athletic performance and mental clarity on a carnivore diet",
      "date": "May 31, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/valerie-heals-from-schizoaffective-disorder-and-anorexia-on-a-carnivore-diet/",
      "title": "Valerie heals from schizoaffective disorder and anorexia on a carnivore diet",
      "date": "March 26, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/donna-manages-graves-disease-and-osteporosis-on-a-carnivore-diet/",
      "title": "Donna manages Graves\u2019 disease and osteporosis on a carnivore diet",
      "date": "July 13, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cindy-gets-off-blood-pressure-medication-on-carnivore-diet/",
      "title": "Cindy gets off blood pressure medication on carnivore diet",
      "date": "May 6, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rebekah-improved-sleep-energy-autoimmune-issues-carnivore-diet/",
      "title": "Rebekah improved autoimmune issues, sleep, gained muscle on carnivore diet",
      "date": "February 8, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/tani-treats-insomnia-scoliosis-conjunctivitis-carnivore-diet/",
      "title": "Tani treats migraines, insomnia, scoliosis, conjunctivitis on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/stephen-improved-cancer-diagnosis-carnivore-diet/",
      "title": "Stephen improved his cancer diagnosis with a carnivore diet.",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/nancy-treated-asthma-hashimotos-sciatica-carnivore-diet/",
      "title": "Nancy improved digestion, skeletal health, skin on carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jodelle-regained-period-lost-anxiety-carnivore-diet/",
      "title": "Jodelle improved hypothyroidism on carnivore diet",
      "date": "October 30, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/robin-heals-epilepsy-seizures-joint-pain-carnivore-diet/",
      "title": "Robin heals from epilepsy, seizures, and joint pain on a carnivore diet",
      "date": "September 30, 2018"
    },
    {
      "visible": false,
      "uri": "https://carnivore.diet/elizabeth-improved-osteoporosis-on-a-carnivore-diet/",
      "title": "Elizabeth improved osteoporosis on a carnivore diet",
      "date": "February 20, 2025"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/osteoporosis/symptoms-causes/syc-20351968",
    "text": "Osteoporosis causes bones to become weak and brittle \u2014 so brittle that a fall or even mild stresses such as bending over or coughing can cause a break. Osteoporosis-related breaks most commonly occur in the hip, wrist or spine."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/inflammatory_bowel_disease.json
{
  "visible": true,
  "name": "Inflammatory Bowel Disease",
  "uri": "inflammatory_bowel_disease",
  "carnivoreDietSearchQueries": [
    "Inflammatory Bowel",
    "IBD"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/a-beginners-introduction-to-the-carnivore-diet/",
    "https://carnivore.diet/anti-nutrients/",
    "https://carnivore.diet/",
    "https://carnivore.diet/carnivore-and-the-art-of-pooping/",
    "https://carnivore.diet/cognitive-function-tips-by-coach-elizabeth-b/",
    "https://carnivore.diet/why-all-the-fuss-over-fiber/",
    "https://carnivore.diet/plants-are-out-to-poison-you/",
    "https://carnivore.diet/no-gallbladder-no-problem/",
    "https://carnivore.diet/lamb-ribs-with-chermoula/",
    "https://carnivore.diet/what-to-eat-on-the-carnivore-diet/",
    "https://carnivore.diet/14-days-of-carnivore-diet/",
    "https://carnivore.diet/is-dietary-fiber-necessary-for-a-healthy-diet-2/",
    "https://carnivore.diet/carnivore-recipes/",
    "https://carnivore.diet/contact/",
    "https://carnivore.diet/carnivore-diet-food-list-meal-plan/",
    "https://carnivore.diet/guides/carnivore-guide/6-transition-bowel-movements/",
    "https://carnivore.diet/meat-and-the-environment/",
    "https://carnivore.diet/keto-bacon-jalapeno-cheese-ball/",
    "https://carnivore.diet/guides/fasting-guide/food-list-meal-plan-and-shopping-list/",
    "https://carnivore.diet/nsvs-nonscale-victories-on-a-carnivore-diet/",
    "https://carnivore.diet/slow-cooker-beef-bone-broth-recipe-crock-pot-option/",
    "https://carnivore.diet/theresa-healed-crohns-disease-and-lost-weight-on-a-carnivore-lifestyle/",
    "https://carnivore.diet/mickis-ms-in-remission-bowel-issues-gone-carnivore-diet/",
    "https://carnivore.diet/emily-j-manages-type-1-diabetes-ibs-strength-pain-and-acne-on-a-carnivore-diet/",
    "https://carnivore.diet/sylvia-eliminated-rheumatoid-arthritis-allergies-and-constipation-on-carnivore-diet/",
    "https://carnivore.diet/sara-j-healed-boils-sarcopenia-and-dysphoric-pre-menstrual-disorder-on-a-carnivore-diet/",
    "https://carnivore.diet/ahmad-improved-energy-anxiety-and-depression-on-a-carnivore-diet/",
    "https://carnivore.diet/kelly-improved-kidney-disease-digestion-carnivore-diet/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/michael-healed-eczema-leaky-gut-carnivore-diet/",
      "title": "Michael C healed eczema, leaky gut, and inflammatory bowel disease on a carnivore diet",
      "date": "May 31, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/tanner-heals-from-crohns-disease-eczema-and-being-underweight-on-a-carnivore-diet/",
      "title": "Tanner heals from Crohn\u2019s disease, eczema, and being underweight on a carnivore diet",
      "date": "June 27, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kim-improved-ulcerative-colitis-boils-migraines-on-carnivore-diet/",
      "title": "Kim improved her ulcerative colitis on a carnivore diet",
      "date": "November 4, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cassie-healed-plantar-fasciitis-edema-carnivore-diet/",
      "title": "Cassie healed from plantar fasciitis, edema, back pain on a carnivore diet",
      "date": "October 13, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ashley-treats-asthma-psoriasis-crohns-rosacea-carnivore-diet/",
      "title": "Ashley treats asthma, psoriasis, crohn\u2019s disease, rosacea on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/patrick-heals-diabetes-ulcerative-colitis-carnivore-diet/",
      "title": "Patrick healed from Ulcerative Colitis on a carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/pyroxidine-improved-skin-ibs-anxiety-carnivore-diet/",
      "title": "Pyroxidine improved skin, IBS, and anxiety on a carnivore diet",
      "date": "November 14, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lindsay-lost-weight-improved-skin-digestion-carnivore-diet/",
      "title": "Lindsay lost weight and improved skin and digestion on carnivore diet",
      "date": "November 13, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mim-improved-reproductive-urinary-health-carnivore-diet/",
      "title": "Mim improved her eczema on a carnivore diet",
      "date": "October 10, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rebekah-improved-sleep-energy-autoimmune-issues-carnivore-diet/",
      "title": "Rebekah improved autoimmune issues, sleep, gained muscle on carnivore diet",
      "date": "February 8, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/nathaniel-improved-digestion-fitness-fatigue-carnivore-diet/",
      "title": "Nathaniel improved his fitness and energy on a carnivore diet",
      "date": "October 11, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/raymond-heals-diverticulitis-plantar-fasciitis-carnivore-diet/",
      "title": "Raymond heals prediabetes, sugar addiction, diverticulitis on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/daniel-improves-digestion-weight-loss-carnivore-diet/",
      "title": "Daniel improves his digestion and weight loss on a carnivore diet",
      "date": "October 5, 2018"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/inflammatory-bowel-disease/symptoms-causes/syc-20353315",
    "text": "Inflammatory bowel disease (IBD) is a term that describes disorders involving long-standing (chronic) inflammation of tissues in your digestive tract. Types of IBD include: Ulcerative colitis and Crohn's disease."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/leaky_gut.json
{
  "visible": true,
  "name": "Leaky Gut",
  "uri": "leaky_gut",
  "carnivoreDietSearchQueries": [
    "Leaky Gut"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/plants-are-out-to-poison-you/",
    "https://carnivore.diet/anti-nutrients/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/marti-healed-leaky-gut-on-a-carnivore-diet/",
      "title": "Marti healed leaky gut on a carnivore diet",
      "date": "May 6, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jules-carnivore-lifestyle-healed-leaky-gut-resolve-multiple-mental-health-issues/",
      "title": "Jules&#039; Carnivore lifestyle healed leaky gut, resolve multiple mental health issues",
      "date": "October 22, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/michael-healed-eczema-leaky-gut-carnivore-diet/",
      "title": "Michael C healed eczema, leaky gut, and inflammatory bowel disease on a carnivore diet",
      "date": "May 31, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/gregory-overcame-weight-lymphedema-high-blood-pressure-prediabetes-on-a-carnivore-diet/",
      "title": "Gregory overcame weight, lymphedema, high blood pressure, prediabetes on a carnivore diet",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/sylvia-eliminated-rheumatoid-arthritis-allergies-and-constipation-on-carnivore-diet/",
      "title": "Sylvia eliminated Rheumatoid Arthritis, allergies, and constipation on carnivore diet",
      "date": "November 24, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/julia-reached-pre-pregnancy-weight-reduced-thyroid-medication-on-a-carnivore-lifestyle/",
      "title": "Julia reached pre-pregnancy weight, reduced thyroid medication on a carnivore lifestyle",
      "date": "March 27, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/parveen-improved-metabolic-thyroid-and-mental-health-on-a-carnivore-diet/",
      "title": "Parveen improved metabolic, thyroid, and mental health on a Carnivore diet",
      "date": "February 21, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rhonda-improved-her-digestive-issues-lost-weight-and-reduced-pain-after-going-on-an-animal-based-diet/",
      "title": "Rhonda improved her digestive issues, lost weight, and reduced pain after going on an animal based diet",
      "date": "February 20, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/laura-healed-allergies-asthma-gi-issues-on-carnivore-diet/",
      "title": "Laura healed her allergies, asthma, GI issues on a carnivore diet",
      "date": "December 24, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mariela-restored-health-damage-veganism/",
      "title": "Mariela restored her health from the damage of veganism",
      "date": "November 27, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/brian-improved-tears-strains-on-carnivore-diet/",
      "title": "Brian no longer suffers from tears and strains on a carnivore diet",
      "date": "October 23, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cassie-healed-plantar-fasciitis-edema-carnivore-diet/",
      "title": "Cassie healed from plantar fasciitis, edema, back pain on a carnivore diet",
      "date": "October 13, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ex-vegan-heals-eczema-regains-health-carnivore-diet/",
      "title": "Ex-vegan heals his eczema and regains his health on a carnivore diet",
      "date": "August 24, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/katya-raw-vegan-improved-digestion-bladder-kidney-carnivore/",
      "title": "Katya improved digestion, bladder and kidney pain on a carnivore diet",
      "date": "March 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/isaac-lost-weight-improved-health-carnivore-diet/",
      "title": "Isaac lost weight (58 lbs) on a carnivore diet",
      "date": "March 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/martin-heartburn-and-sleep-on-a-carnivore-diet/",
      "title": "Martin heartburn and sleep on a carnivore diet",
      "date": "December 3, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/terese-improved-sleep-mood-digestion-asthma-carnivore-diet/",
      "title": "Terese increased her energy on a carnivore diet",
      "date": "November 3, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/christopher-improves-allergies-vision-leaky-gut-carnivore-diet/",
      "title": "Christopher improves allergies, vision, athlete&#039;s foot on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/isabel-improved-digestion-liver-mental-health-carnivore-diet/",
      "title": "Isabel cured her IBS on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/warren-improved-arthritis-carnivore-diet/",
      "title": "Warren improved arthritis on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/wade-heals-anxiety-depression-strep-throat-carnivore-diet/",
      "title": "Wade heals anxiety, depression, strep throat, joint pain on carnivore diet",
      "date": "October 30, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/noelle-improved-hypertension-hashimotos-on-a-carnivore-diet/",
      "title": "Noelle improved hypertension and Hashimoto&#039;s on a carnivore diet",
      "date": "March 7, 2025"
    }
  ],
  "definition": {
    "source": "https://my.clevelandclinic.org/health/diseases/22724-leaky-gut-syndrome",
    "text": "Leaky gut syndrome is a hypothetical condition that\u2019s not currently recognized as a medical diagnosis. It\u2019s based on the concept of increased intestinal permeability, which occurs in some gastrointestinal diseases."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/dental_plaque.json
{
  "visible": true,
  "name": "Dental Plaque",
  "uri": "dental_plaque",
  "carnivoreDietSearchQueries": [
    "Plaque"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/dental-health-tips-by-coach-tracy-k/",
    "https://carnivore.diet/nsvs-nonscale-victories-on-a-carnivore-diet/",
    "https://carnivore.diet/carnivore-for-alzheimers-prevention-a-no-brainer/",
    "https://carnivore.diet/cognitive-function-tips-by-coach-elizabeth-b/",
    "https://carnivore.diet/sara-manages-type-1-diabetes-on-a-low-carb-diet/",
    "https://carnivore.diet/nanci-heals-osteopenia-carnivore-diet/",
    "https://carnivore.diet/mariela-restored-health-damage-veganism/",
    "https://carnivore.diet/isaac-lost-weight-improved-health-carnivore-diet/",
    "https://carnivore.diet/danny-improved-liver-health-sleep-apnea-carnivore-diet/",
    "https://carnivore.diet/aaron-treats-auto-immune-issues-depression-carnivore-diet/",
    "https://carnivore.diet/sarah-improves-autoimmune-conditions-arthritis-carnivore-diet/",
    "https://carnivore.diet/rishi-improved-digestion-body-composition-carnivore-diet/",
    "https://carnivore.diet/alex-improved-pain-carnivore-diet/",
    "https://carnivore.diet/stephen-improved-psoriatic-arthritis-and-depression-on-the-carnivore-diet/",
    "https://carnivore.diet/stepanka-improves-depression-anorexia-and-bulimia-on-a-carnivore-diet/",
    "https://carnivore.diet/bill-healed-from-diabetes-arthritis-and-depression-on-the-carnivore-diet/",
    "https://carnivore.diet/laura-improved-anxiety-depression-skin-issues-carnivore-diet/",
    "https://carnivore.diet/todd-overcame-gout-depression-and-anxiety-on-a-carnivore-diet/",
    "https://carnivore.diet/alysha-improved-digestion-and-depression-on-the-carnivore-diet/",
    "https://carnivore.diet/mary-improved-fatigue-depression-and-anxiety-on-the-carnivore-diet/",
    "https://carnivore.diet/pim-improved-anxiety-depression-and-ibs-on-the-carnivore-diet/",
    "https://carnivore.diet/marina-manages-depression-and-weight-on-a-carnivore-diet/",
    "https://carnivore.diet/ashley-sarah-fight-depression-on-a-carnivore-diet/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/vajid-improved-endurance-and-weight-loss-on-the-carnivore-diet/",
      "title": "Vajid improved endurance and weight loss on the carnivore diet",
      "date": "September 7, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/katya-raw-vegan-improved-digestion-bladder-kidney-carnivore/",
      "title": "Katya improved digestion, bladder and kidney pain on a carnivore diet",
      "date": "March 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rix-improved-skin-chronic-pain-digestion-mood-carnivore-diet/",
      "title": "Mike C. improved skin, chronic pain, digestion and mood on carnivore diet",
      "date": "February 6, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ekaterina-ex-vegan-improved-hormonal-health-carnivore-diet/",
      "title": "Ekaterina improved digestion, hormonal health and PCOS on carnivore diet",
      "date": "December 18, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/david-improves-weight-loss-ibs-sciatic-issues-carnivore-diet/",
      "title": "David improves IBS, dental hygiene, sciatic issues on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/bruce-fixes-migraines-psoriasis-carnivore-diet/",
      "title": "Bruce fixes migraines, psoriasis, environmental concerns on carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/udo-improved-dental-health-mood-mental-health-carnivore-diet/",
      "title": "Udo lost weight and improved mental health on a carnivore diet",
      "date": "October 10, 2018"
    },
    {
      "visible": false,
      "uri": "https://carnivore.diet/stephen-improved-psoriatic-arthritis-on-the-carnivore-diet/",
      "title": "Stephen improved psoriatic arthritis and depression on the carnivore diet",
      "date": "October 19, 2024"
    }
  ],
  "definition": {
    "source": "https://my.clevelandclinic.org/health/diseases/10953-plaque",
    "text": "Dental plaque is a sticky film of bacteria that constantly forms on your teeth. It\u2019s normal to produce plaque. But if you don\u2019t remove plaque with routine dental cleanings and daily brushing and flossing, it can cause cavities, gum disease and other oral health issues."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/tendinitis.json
{
  "visible": true,
  "name": "Tendinitis",
  "uri": "tendinitis",
  "carnivoreDietSearchQueries": [
    "Tendinitis"
  ],
  "filteredAnecdotes": [],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/joels-arthritis-spine-issues-and-chronic-tendinitis-in-full-remission-on-carnivore-diet/",
      "title": "Joel\u2019s arthritis, spine issues and chronic tendinitis in full remission on carnivore diet",
      "date": "December 30, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lee-anne-healed-from-severe-onset-of-tendinitis-lower-back-pain-long-menstrual-cycles-hot-flashes-migraines-yeast-infections-fibroids-mmpi-depression-anxiety-and-more-on-a-carnivore-diet/",
      "title": "Lee Anne healed her severe tendinitis, depression, anxiety on a carnivore diet",
      "date": "February 13, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chandler-treats-vasculitis-tendinitis-carnivore-diet/",
      "title": "Chandler treats vasculitis, tendinitis, piriformis syndrome on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chris-improved-arthritis-tendinitis-carnivore-diet/",
      "title": "Chris improved arthritis, tendinitis, and lost weight on carnivore diet",
      "date": "March 21, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/heath-improved-tendinitis-dandruff-hemorrhoids-carnivore-diet/",
      "title": "Heath fixed his metabolic syndrome on carnivore diet",
      "date": "February 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/eric-improved-cardiovascular-health-skin-carnivore-diet/",
      "title": "Eric improved cardiovascular health on carnivore diet",
      "date": "December 21, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/patrick-improved-digestion-body-composition-carnivore-diet/",
      "title": "Patrick improved digestion, mood, energy, body composition on carnivore diet",
      "date": "November 13, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chris-improved-digestion-mood-carnivore-diet/",
      "title": "Chris improved digestion and mood on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/dain-improved-sleep-anxiety-dandruff-tinnitus-carnivore-diet/",
      "title": "Dain improves in sleep, anxiety, dandruff, tinnitus on carnivore diet",
      "date": "October 30, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chris-improved-arthritis-tendinitis-and-lost-weight-on-carnivore-diet/",
      "title": "Chris Improved Arthritis and Tendinitis On a Carnivore Diet",
      "date": "January 1, 2018"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/tendinitis/symptoms-causes/syc-20378243",
    "text": "Tendinitis is inflammation of the thick fibrous cords that attach muscle to bone. These cords are called tendons. The condition causes pain and tenderness just outside a joint. Tendinitis can occur in any tendon. But it's most common around shoulders, elbows, wrists, knees and heels."
  },
  "papers": [],
  "articles": [],
  "videos": []
}
