=== codemonstur/site-plants-cause-disease/src/main/resources/schema/disease.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "visible": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "uri": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "filteredAnecdotes": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "carnivoreDietSearchQueries": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "anecdotes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "visible": {
            "type": "boolean"
          },
          "uri": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        }
      }
    },
    "definition": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "source": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "required": [
        "source",
        "text"
      ]
    },
    "see": {
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "uri",
        "name"
      ]
    },
    "papers": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "articles": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "videos": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "visible",
    "name",
    "uri"
  ]
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/atherosclerosis.json
{
  "visible": true,
  "name": "Atherosclerosis",
  "uri": "atherosclerosis",
  "carnivoreDietSearchQueries": [
    "Atherosclerosis"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/meat-the-ultimate-superfood/",
    "https://carnivore.diet/thyroid-function-tips-by-coach-elizabeth-b/",
    "https://carnivore.diet/heart-health-resources/",
    "https://carnivore.diet/mariela-restored-health-damage-veganism/",
    "https://carnivore.diet/isaac-lost-weight-improved-health-carnivore-diet/"
  ],
  "anecdotes": [],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/arteriosclerosis-atherosclerosis/symptoms-causes/syc-20350569",
    "text": "Atherosclerosis is a specific type of arteriosclerosis. Atherosclerosis is the buildup of fats, cholesterol and other substances in and on the artery walls. This buildup is called plaque. The plaque can cause arteries to narrow, blocking blood flow. The plaque can also burst, leading to a blood clot. Although atherosclerosis is often considered a heart problem, it can affect arteries anywhere in the body. Atherosclerosis can be treated. Healthy lifestyle habits can help prevent atherosclerosis."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/insomnia.json
{
  "visible": true,
  "name": "Insomnia",
  "uri": "insomnia",
  "carnivoreDietSearchQueries": [
    "Insomnia"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/carnivore-diet-faq/",
    "https://carnivore.diet/carnivore-diet-success-stories/",
    "https://carnivore.diet/getting-started-on-the-carnivore-diet-tips-by-coach-kiki-f/",
    "https://carnivore.diet/cognitive-function-tips-by-coach-elizabeth-b/",
    "https://carnivore.diet/thyroid-function-tips-by-coach-elizabeth-b/",
    "https://carnivore.diet/anti-nutrients/",
    "https://carnivore.diet/carnivore-diet-old/",
    "https://carnivore.diet/luke-reversed-long-covid-with-the-carnivore-diet/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/reagan-stuttering-insomnia-obesity/",
      "title": "Reagan heals from stuttering, stress, anxiety, pain, aches, dizziness, insomnia, obesity",
      "date": "July 18, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/joseph-lost-100-pounds-cured-migraines-insomnia-pre-diabetes-and-gerd-on-a-carnivore-diet/",
      "title": "Joseph lost 100 pounds, cured migraines, insomnia, pre-diabetes, and GERD on a Carnivore diet",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cameron-resolved-ibs-insomnia-anxiety-carnivore-lifestyle/",
      "title": "Cameron resolved his IBS, insomnia, and anxiety on a carnivore lifestyle",
      "date": "November 24, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/david-remedies-ibs-insomnia-improves-energy-carnivore-diet/",
      "title": "David remedies IBS and insomnia, improves mental clarity on carnivore diet",
      "date": "October 31, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/tani-treats-insomnia-scoliosis-conjunctivitis-carnivore-diet/",
      "title": "Tani treats migraines, insomnia, scoliosis, conjunctivitis on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cobus-improves-weight-hepatomegaly-insomnia-carnivore-diet/",
      "title": "Cobus improves weight loss, hepatomegaly, and insomnia on a carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/pim-improved-anxiety-depression-and-ibs-on-the-carnivore-diet/",
      "title": "Pim improved anxiety, depression, and IBS on the carnivore diet",
      "date": "August 30, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ashley-sarah-fight-depression-on-a-carnivore-diet/",
      "title": "Ashley &amp; Sarah overcome depression on a carnivore diet",
      "date": "August 17, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ollie-improves-depersonalisation-hallucinations-and-cyclothymia-on-a-low-carb-diet/",
      "title": "Ollie improves depersonalisation, hallucinations, and cyclothymia on a low-carb diet",
      "date": "January 6, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/joel-is-off-all-medications-and-his-doctors-on-a-carnivore-lifestyle/",
      "title": "Joel is off all medications and his doctors on a carnivore lifestyle",
      "date": "February 21, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/debbie-reversed-t2d-high-blood-pressure-migraines-psoriasis-on-carnivore-lifestyle/",
      "title": "Debbie reversed T2D, high blood pressure, migraines, psoriasis on Carnivore lifestyle",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/robert-healed-his-body-after-28-years-of-being-a-vegan-on-a-carnivore-diet/",
      "title": "Robert Healed his body after 28 years of being a vegan on a carnivore diet",
      "date": "April 3, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/volodymir-eliminated-acid-reflux-ibs-pyelonephritis-and-alzheimers-on-carnivore-diet/",
      "title": "Volodymir eliminated acid reflux, IBS, pyelonephritis, and Alzheimer&#039;s on carnivore diet",
      "date": "March 30, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/craig-healed-gut-migraines-sleep-and-sinusitis-on-a-carnivore-lifestyle/",
      "title": "Craig healed gut, migraines, sleep, and sinusitis on a carnivore lifestyle",
      "date": "March 27, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/samaria-has-reversed-tardive-dyskinesia-on-a-carnivore-lifestyle/",
      "title": "Samaria has reversed tardive dyskinesia on a carnivore lifestyle",
      "date": "March 26, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/andy-cured-acid-reflux-ibs-hay-fever-and-depression-on-a-carnivore-diet/",
      "title": "Andy cured acid reflux, IBS, hay fever, and depression on a Carnivore diet",
      "date": "March 26, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/nicki-k-healed-fibromyalgia-on-a-carnivore-diet/",
      "title": "Nicki K healed Fibromyalgia on a carnivore diet",
      "date": "March 22, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/maria-improved-her-mood-athletic-performance-digestion-cognitive-and-sleep-on-a-carnivore-diet/",
      "title": "Maria improved her moods, gained better athletic performance &amp; cognitive function on a carnivore diet",
      "date": "February 14, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kiki-healing-weakness-low-thyroid-vegan-to-carnivore-diet/",
      "title": "Kiki is healing from weakness, low thyroid, inflammation on carnivore diet",
      "date": "October 18, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lori-improved-digestion-sugar-cravings-anxiety-carnivore-diet/",
      "title": "Lori improved digestion, sugar cravings, and anxiety on a carnivore diet",
      "date": "March 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jurriaan-improved-mood-sleep-energy-pain-carnivore-diet/",
      "title": "Jurriaan fixed his depression on a carnivore diet",
      "date": "February 26, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rebekah-improved-sleep-energy-autoimmune-issues-carnivore-diet/",
      "title": "Rebekah improved autoimmune issues, sleep, gained muscle on carnivore diet",
      "date": "February 8, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mathieu-improved-immune-system-allergies-carnivore-diet/",
      "title": "Mathieu improved fitness, energy, cardiovascular health on carnivore diet",
      "date": "October 11, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/woman-treats-narcolepsy-retinopathy-carnivore-diet/",
      "title": "Woman treats Crohn&#039;s, asthma, narcolepsy, hypothyroidism on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/raymond-heals-diverticulitis-plantar-fasciitis-carnivore-diet/",
      "title": "Raymond Heals Prediabetes and More With the Carnivore Diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kelly-heals-ibs-liver-nodules-depression-carnivore-diet/",
      "title": "Kelly heals IBS, high blood pressure, liver nodules on carnivore diet",
      "date": "September 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/anonymous-improved-digestion-body-composition-carnivore-diet/",
      "title": "Anonymous improved digestion, sleep, body composition on carnivore diet",
      "date": "December 15, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/c-d-improved-plantar-fasciitis-nose-bleeds-carnivore-diet/",
      "title": "C.D. improved plantar fasciitis and nose bleeds on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lynsey-improved-mental-health-mouth-ulcers-carnivore-diet/",
      "title": "Lynsey treated mouth ulcers on carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/david-heals-allergies-hypersensitivity-sleep-carnivore-diet/",
      "title": "David heals allergies, hypersensitivity, sleep issues on carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/leo-improved-anxiety-mood-multiple-sclerosis-carnivore-diet/",
      "title": "Leo improved mood disorder, multiple sclerosis, digestion on carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/richard-treated-arthritis-joint-pain-fatigue-carnivore-diet/",
      "title": "Richard improved his arthritis and joint pain on a carnivore diet",
      "date": "October 5, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/margaret-heals-digestion-mood-sleep-fatigue-carnivore-diet/",
      "title": "Margaret heals digestion, mood, sleep, and fatigue on a carnivore diet",
      "date": "October 4, 2018"
    }
  ],
  "definition": {
    "source": "https://my.clevelandclinic.org/health/diseases/12119-insomnia",
    "text": "Insomnia is when you experience disruptions in how you feel or function because you aren\u2019t sleeping well or sleeping enough. About 10% of the world\u2019s population experience insomnia that qualifies as a medical condition. It\u2019s usually not dangerous, and there are many ways \u2014 including medications and mental health options \u2014 to treat it."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/indigestion.json
{
  "visible": true,
  "name": "Indigestion",
  "uri": "indigestion",
  "carnivoreDietSearchQueries": [
    "Dyspepsia",
    "Indigestion"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/getting-started-carnivore-transition-period-by-coach-elizabeth-b/",
    "https://carnivore.diet/better-life-carnivore-diet/",
    "https://carnivore.diet/no-gallbladder-no-problem/",
    "https://carnivore.diet/carnivore-diet-tips/",
    "https://carnivore.diet/anti-nutrients/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/brian-improved-digestion-and-energy-on-the-carnivore-diet/",
      "title": "Brian improved digestion and energy on the carnivore diet Brian improved digestion on the carnivore diet",
      "date": "August 25, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/adam-transformed-weight-digestion-and-fitness-on-the-carnivore-diet/",
      "title": "Adam transformed weight, digestion, and fitness on the carnivore diet",
      "date": "June 26, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/barbara-s-heals-from-anxiety-and-digestive-issues-on-a-carnivore-diet/",
      "title": "Barbara S heals from anxiety and digestive issues on a carnivore diet",
      "date": "April 19, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/volodymir-eliminated-acid-reflux-ibs-pyelonephritis-and-alzheimers-on-carnivore-diet/",
      "title": "Volodymir eliminated acid reflux, IBS, pyelonephritis, and Alzheimer&#039;s on carnivore diet",
      "date": "March 30, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/devin-improved-nerve-pain-hormonal-balance-and-eliminated-seizures-on-a-carnivore-diet/",
      "title": "Devin improved nerve pain, hormonal balance, and eliminated seizures on a carnivore diet",
      "date": "February 17, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/robert-anxiety-free-switching-carnivore-diet-lost-weight/",
      "title": "Robert is no longer sore, is now free from anxiety on a carnivore diet",
      "date": "August 24, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lori-improved-digestion-sugar-cravings-anxiety-carnivore-diet/",
      "title": "Lori improved digestion, sugar cravings, and anxiety on a carnivore diet",
      "date": "March 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/michael-improved-addiction-arthritis-fatigue-carnivore-diet/",
      "title": "Michael improved mood, mental health, skin, vision on carnivore diet",
      "date": "November 1, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/charlene-improves-sleep-mental-health-lyme-carnivore-diet/",
      "title": "Charlene improves sleep, cardiovascular health, digestion on carnivore diet",
      "date": "October 5, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/joe-improved-metabolic-flexibility-carnivore-fasting-lifestyle/",
      "title": "Joe improved metabolic flexibility on carnivore fasting lifestyle",
      "date": "May 15, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/matt-improved-digestion-headaches-energy-carnivore-diet/",
      "title": "Matt improved his energy on carnivore diet",
      "date": "March 13, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/sara-lost-weight-improved-menstrual-cramping-carnivore-diet/",
      "title": "Sara lost weight and improved her menstrual cramping on a carnivore diet",
      "date": "December 17, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/isabel-improved-digestion-liver-mental-health-carnivore-diet/",
      "title": "Isabel cured her IBS on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lucie-improved-migraines-carnivore-diet/",
      "title": "Lucie improved migraines on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/amber-improved-hirsutism-carnivore-diet/",
      "title": "Amber improved hirsutism with a carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/wade-heals-anxiety-depression-strep-throat-carnivore-diet/",
      "title": "Wade heals anxiety, depression, strep throat, joint pain on carnivore diet",
      "date": "October 30, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ankur-improved-cholesterol-and-sleep-on-a-carnivore-diet/",
      "title": "Ankur improved cholesterol and sleep on a carnivore diet",
      "date": "March 12, 2025"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/indigestion/symptoms-causes/syc-20352211",
    "text": "Indigestion \u2014 also called dyspepsia or an upset stomach \u2014 is discomfort in your upper abdomen. Indigestion describes certain symptoms, such as belly pain and a feeling of fullness soon after you start eating, rather than a specific disease. Indigestion can also be a symptom of other digestive disorders."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/postural_orthostatic_tachycardia_syndrome.json
{
  "visible": true,
  "name": "Postural Orthostatic Tachycardia Syndrome",
  "uri": "postural_orthostatic_tachycardia_syndrome",
  "carnivoreDietSearchQueries": [
    "Postural Orthostatic Tachycardia Syndrome",
    "POTS"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/nsvs-nonscale-victories-on-a-carnivore-diet/",
    "https://carnivore.diet/tips-for-cooking-carnivore-meals-by-coach-tracy-k/",
    "https://carnivore.diet/carnivore-diet-tips-by-coach-tracy-k/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/eddie-heals-from-ehlers-danlos-syndrome-on-a-carnivore-diet/",
      "title": "Eddie heals from Ehlers-Danlos syndrome on a carnivore diet",
      "date": "May 9, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jason-improves-lymes-disease-chronic-fatigue-carnivore-diet/",
      "title": "Jason improves Chronic Fatigue on carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/relief-from-eds-pots/",
      "title": "Amy finds relief from EDS &amp; POTS with Carnivore Diet",
      "date": "June 3, 2025"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rachel-gets-relief-from-ehlers-danlos-syndrome-dysautonomia-pots-on-the-carnivore-diet/",
      "title": "Rachel gets relief from Ehlers-Danlos Syndrome, Dysautonomia (POTS) on the carnivore diet",
      "date": "November 3, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/carrie-improved-mast-cell-activation-syndrome-on-a-keto-diet/",
      "title": "Carrie improved mast cell activation syndrome on a keto diet",
      "date": "March 10, 2025"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ankur-improved-cholesterol-and-sleep-on-a-carnivore-diet/",
      "title": "Ankur improved cholesterol and sleep on a carnivore diet",
      "date": "March 12, 2025"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/leo-improved-anxiety-and-skin-issues-on-a-carnivore-diet/",
      "title": "Leo improved anxiety and skin issues on a carnivore diet",
      "date": "March 10, 2025"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/maranda-improved-fibromyalgia-hypoglycemia-on-carnivore-diet/",
      "title": "Maranda improved fibromyalgia &amp; hypoglycemia on carnivore diet",
      "date": "March 6, 2025"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ashley-manages-multiple-sclerosis-on-the-carnivore-diet/",
      "title": "Ashley manages multiple sclerosis on the carnivore diet",
      "date": "March 22, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/melissa-and-tom-are-navigating-cancer-on-the-carnivore-diet/",
      "title": "Melissa And Tom Are Navigating Cancer On The Carnivore Diet",
      "date": "September 18, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kristen-feels-alive-for-the-first-time-on-a-carnivore-diet/",
      "title": "Kristen feels alive for the first time on a carnivore diet",
      "date": "May 6, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/tammy-reversed-arthritis-simple-seizures-pcos-on-a-carnivore-lifestyle/",
      "title": "Tammy reversed arthritis, simple seizures, PCOS on a Carnivore lifestyle",
      "date": "December 30, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/aaron-got-rid-of-sugar-cravings-and-built-muscle-on-a-carnivore-based-lifestyle/",
      "title": "Aaron got rid of sugar cravings, and built muscle on a Carnivore based lifestyle",
      "date": "April 7, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/robert-healed-his-body-after-28-years-of-being-a-vegan-on-a-carnivore-diet/",
      "title": "Robert Healed his body after 28 years of being a vegan on a carnivore diet",
      "date": "April 3, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/janice-solved-digestive-problems-anxiety-on-carnivore-diet/",
      "title": "Janice solved her digestive problems and anxiety on a carnivore diet",
      "date": "February 8, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/tiffany-overcame-decades-food-addiction-on-carnivore-diet/",
      "title": "Tiffany overcame decades of food addiction on a carnivore diet",
      "date": "December 31, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mariela-restored-health-damage-veganism/",
      "title": "Mariela restored her health from the damage of veganism",
      "date": "November 27, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jose-got-in-control-of-his-cravings-on-a-carnivore-diet/",
      "title": "Jose got in control of his cravings on a carnivore diet",
      "date": "October 24, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ren-healing-chronic-pain-migraines-depression-carnivore-diet/",
      "title": "Ren is healing from chronic pain, migraines, depression a carnivore diet",
      "date": "September 5, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mark-improved-blood-pressure-fasting-meat-centric-keto-lifestyle/",
      "title": "Mark improved respiration with a fasting keto-carnivore diet",
      "date": "May 11, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/isaac-lost-weight-improved-health-carnivore-diet/",
      "title": "Isaac lost weight (58 lbs) on a carnivore diet",
      "date": "March 21, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/leri-improves-back-pain-mental-clarity-carnivore-diet/",
      "title": "Leri drastically improves mental clarity on carnivore diet",
      "date": "February 26, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/nathan-improves-back-pain-joint-pain-sleep-carnivore-diet/",
      "title": "Nathan improves back pain, joint pain, and sleep on a carnivore diet",
      "date": "October 31, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mike-improved-eczema-cravings-sleep-weight-carnivore-diet/",
      "title": "Mike improved his eczema, cravings, sleep and weight on a carnivore diet",
      "date": "March 13, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/autumn-improved-psoriasis-carnivore-diet/",
      "title": "Autumn improved psoriasis on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/yuri-improved-skin-pain-sleep-carnivore-diet/",
      "title": "Yuri improved his skin, pain and sleep with a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lucie-improved-migraines-carnivore-diet/",
      "title": "Lucie improved migraines on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/biccy-improved-anxiety-carnivore-diet/",
      "title": "Nick improved anxiety on a carnivore diet",
      "date": "November 1, 2018"
    }
  ],
  "definition": {
    "source": "",
    "text": ""
  },
  "papers": [],
  "articles": [],
  "videos": []
}
