=== codemonstur/site-plants-cause-disease/src/main/resources/schema/disease.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "visible": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "uri": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "filteredAnecdotes": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "carnivoreDietSearchQueries": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "anecdotes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "visible": {
            "type": "boolean"
          },
          "uri": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        }
      }
    },
    "definition": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "source": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "required": [
        "source",
        "text"
      ]
    },
    "see": {
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "uri",
        "name"
      ]
    },
    "papers": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "articles": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "videos": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "visible",
    "name",
    "uri"
  ]
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/celiac_disease.json
{
  "visible": true,
  "name": "Celiac Disease",
  "uri": "celiac_disease",
  "carnivoreDietSearchQueries": [
    "Celiac",
    "Coeliac"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/anti-nutrients/",
    "https://carnivore.diet/melanie-put-raynauds-syndrome-into-remission-and-improved-libido-on-a-carnivore-lifestyle/",
    "https://carnivore.diet/john-lost-weight-improved-pain-skin-carnivore-diet/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/stefania-controls-autoimmune-disorders-celiac-and-hashimotos-on-a-carnivore-lifestyle/",
      "title": "Stefania controls autoimmune disorders, celiac and Hashimotos on a carnivore lifestyle",
      "date": "March 20, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/mg-treated-celiac-chrons-disease-carpal-tunnel-carnivore-diet/",
      "title": "M. G. treated celiac, Crohn\u2019s disease, carpal tunnel, TMJ on carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rachel-gets-relief-from-ehlers-danlos-syndrome-dysautonomia-pots-on-the-carnivore-diet/",
      "title": "Rachel gets relief from Ehlers-Danlos Syndrome, Dysautonomia (POTS) on the carnivore diet",
      "date": "November 3, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/travis-was-paralyzed-and-overmedicated-and-the-carnivore-diet-gave-him-life-and-mobility/",
      "title": "Travis was paralyzed and overmedicated and the carnivore diet gave him life and mobility",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/touko-went-from-87kg-to-72kg-on-a-carnivore-lifestyle/",
      "title": "Touko went from 87kg to 72kg on a carnivore lifestyle",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jenell-is-free-from-chronic-pain-ibs-symptoms-and-panic-disorders-on-a-carnivore-diet/",
      "title": "Jenell is free from chronic pain, IBS symptoms, and panic disorders on a carnivore diet",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/erin-ditched-plants-eliminated-eczema/",
      "title": "Erin ditched the plants and eliminated her eczema",
      "date": "October 27, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/rebekah-improved-sleep-energy-autoimmune-issues-carnivore-diet/",
      "title": "Rebekah improved autoimmune issues, sleep, gained muscle on carnivore diet",
      "date": "February 8, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/joette-improved-depression-sleep-hormones-carnivore-diet/",
      "title": "Joette got off 24 medications on carnivore diet",
      "date": "January 3, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/carmen-improved-digestion-heavy-periods-carnivore-diet/",
      "title": "Carmen improved her digestion and heavy periods on a carnivore diet",
      "date": "November 22, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/trey-improved-digestion-anxiety-depression-carnivore-diet/",
      "title": "Trey improved digestion, fitness, anxiety and depression on carnivore diet",
      "date": "November 21, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/virgilia-improves-digestion-migraines-skin-carnivore-diet/",
      "title": "Virgilia improves digestion, joint pain, migraines, skin on carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/michael-treats-tonsillectomy-weakness-fractures-carnivore-diet/",
      "title": "Michael treats coeliac disease on carnivore diet",
      "date": "September 30, 2018"
    },
    {
      "visible": false,
      "uri": "https://carnivore.diet/tammy-heals-from-arthritis-and-depression-on-a-carnivore-diet/",
      "title": "Tammy heals from arthritis and depression on a carnivore diet",
      "date": "February 6, 2025"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/celiac-disease/symptoms-causes/syc-20352220",
    "text": "Celiac disease is an illness caused by an immune reaction to eating gluten. Gluten is a protein found in foods containing wheat, barley or rye."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/rectocele.json
{
  "visible": true,
  "name": "Rectocele",
  "uri": "rectocele",
  "carnivoreDietSearchQueries": [
    "Rectocele"
  ],
  "filteredAnecdotes": [],
  "definition": {
    "source": "https://fascrs.org/patients/diseases-and-conditions/a-z/rectocele",
    "text": "A rectocele is a bulging of the front wall of the rectum into the back wall of the vagina. The rectum is the bottom section of your colon (large intestine). This is a very common problem that often does not produce symptoms. Other pelvic organs can bulge into the vagina, including the bladder (cystocele) and the small intestines (enterocele), producing similar problems."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/rectal_prolapse.json
{
  "visible": true,
  "name": "Rectal Prolapse",
  "uri": "rectal_prolapse",
  "carnivoreDietSearchQueries": [
    "Prolapse"
  ],
  "filteredAnecdotes": [],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/jl-healed-prolapsed-pelvic-floor-digestion-carnivore-diet/",
      "title": "JL healed her prolapsed pelvic floor on a carnivore diet",
      "date": "September 12, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/melissa-improved-pcos-endometriosis-carnivore-diet/",
      "title": "Melissa improved chronic fatigue, PCOS and endometriosis on carnivore diet",
      "date": "January 2, 2020"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/rectal-prolapse/symptoms-causes/syc-20352837",
    "text": "Rectal prolapse happens when part of the large intestine's lowest section, the rectum, slips outside the muscular opening at the end of the digestive tract known as the anus. While rectal prolapse may cause pain, it's rarely a medical emergency."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/attention_deficit_disorder.json
{
  "visible": true,
  "name": "Attention Deficit Disorder",
  "uri": "attention_deficit_disorder",
  "carnivoreDietSearchQueries": [
    "Attention Deficit Disorder"
  ],
  "filteredAnecdotes": [],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/alexander-improves-focus-attention-and-gastrointestinal-issues-on-a-carnivore-diet/",
      "title": "Alexander improves focus, attention, and gastrointestinal issues on a carnivore diet",
      "date": "June 15, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jim-improves-cardiovascular-health-joint-pain-carnivore-diet/",
      "title": "Jim improves cardiovascular health, joint pain, weight loss on carnivore diet",
      "date": "October 31, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/diane-treats-migraines-adhd-sleep-issues-carnivore-diet/",
      "title": "Diane treats ADD on a carnivore diet",
      "date": "October 30, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/robert-anxiety-free-switching-carnivore-diet-lost-weight/",
      "title": "Robert is no longer sore, is now free from anxiety on a carnivore diet",
      "date": "August 24, 2020"
    }
  ],
  "definition": {
    "source": "",
    "text": ""
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/flatulence.json
{
  "visible": true,
  "name": "Flatulence",
  "uri": "flatulence",
  "carnivoreDietSearchQueries": [
    "Farting",
    "Flatulence"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/carnivore-and-the-art-of-pooping/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/dave-improves-stroke-symptoms-on-carnivore-diet/",
      "title": "Dave improves stroke symptoms on carnivore diet",
      "date": "January 6, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/alexandre-improved-mental-health-sex-skin-carnivore-diet/",
      "title": "Alexandre improved digestion, fitness, mood, mental health on carnivore diet",
      "date": "October 5, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jodey-improved-digestion-mood-body-composition-carnivore-diet/",
      "title": "Jodey improved body composition on a carnivore diet",
      "date": "November 21, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/pyroxidine-improved-skin-ibs-anxiety-carnivore-diet/",
      "title": "Pyroxidine improved skin, IBS, and anxiety on a carnivore diet",
      "date": "November 14, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lindsay-lost-weight-improved-skin-digestion-carnivore-diet/",
      "title": "Lindsay lost weight and improved skin and digestion on carnivore diet",
      "date": "November 13, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/gabby-lost-weight-healed-digestion-anxiety-carnivore-diet/",
      "title": "Gabby improved hormonal imbalances on a carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ekaterina-ex-vegan-improved-hormonal-health-carnivore-diet/",
      "title": "Ekaterina improved digestion, hormonal health and PCOS on carnivore diet",
      "date": "December 18, 2019"
    }
  ],
  "definition": {
    "source": "https://www.healthline.com/health/gas-flatulence",
    "text": "Also known as farting, passing wind, or having gas, flatulence is a medical term for releasing gas from the digestive system through the anus. It happens when gas collects inside the digestive system and is a normal process."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/ulcerative_colitis.json
{
  "visible": true,
  "name": "Ulcerative Colitis",
  "uri": "ulcerative_colitis",
  "carnivoreDietSearchQueries": [
    "Ulcerative Colitis"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/nsvs-nonscale-victories-on-a-carnivore-diet/",
    "https://carnivore.diet/is-dietary-fiber-necessary-for-a-healthy-diet-2/",
    "https://carnivore.diet/patient-testimonials-eliminating-medication-on-carnivore-diet/",
    "https://carnivore.diet/no-gallbladder-no-problem/",
    "https://carnivore.diet/carnivore-diet-success-stories/",
    "https://carnivore.diet/fasting-coach-certification/mock-interview/",
    "https://carnivore.diet/robert-improved-ulcerative-colitis-carnivore-diet/",
    "https://carnivore.diet/bruce-improved-digestion-and-ileostomy-output-on-a-carnivore-diet/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/mike-improved-diarrhea-and-ulcerative-colitis-on-the-carnivore-diet/",
      "title": "Mike improved diarrhea and ulcerative colitis on the carnivore diet",
      "date": "October 31, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/robert-improved-ulcerative-colitis-on-the-carnivore-diet/",
      "title": "From Carbs to Carnivore: How Robert Found Strength in Simplicity",
      "date": "August 29, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/travis-improved-mental-health-skin-issues-ulcerative-colitis-carnivore-diet/",
      "title": "Travis Improved Mental Health &amp; More On Carnivore Diet",
      "date": "January 6, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kat-heals-from-ulcerative-colitis-asthma-and-lyme-disease-on-the-carnivore-diet/",
      "title": "Kat heals from ulcerative colitis, asthma, and Lyme disease on the carnivore diet",
      "date": "October 12, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ex-plant-eater-josie-defeats-ulcerative-colitis/",
      "title": "Ex-Plant Eater Josie Defeats Ulcerative Colitis",
      "date": "June 26, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/stephen-healed-ulcerative-colitis-on-keto-and-seborrheic-dermatitis-on-carnivore-lifestyle/",
      "title": "Stephen healed Ulcerative Colitis on Keto and Seborrheic Dermatitis on carnivore lifestyle",
      "date": "February 15, 2022"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/swetas-carnivore-lifestyle-reversed-ulcerative-colitis-and-got-her-off-medication/",
      "title": "Sweta&#039;s carnivore lifestyle reversed ulcerative colitis and got her off medication",
      "date": "December 30, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/grant-no-ulcerative-colitis-symptoms-on-a-carnivore-diet/",
      "title": "Grant no longer has ulcerative colitis symptoms on a carnivore diet",
      "date": "December 12, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kim-improved-ulcerative-colitis-boils-migraines-on-carnivore-diet/",
      "title": "Kim improved her ulcerative colitis on a carnivore diet",
      "date": "November 4, 2020"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/douglas-improved-digestion-ulcerative-colitis-carnivore-diet/",
      "title": "Douglas improved digestion and treated ulcerative colitis on carnivore diet",
      "date": "November 2, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/alberto-resolves-ulcerative-colitis-energy-carnivore-diet/",
      "title": "Alberto resolves ulcerative colitis, improves energy on carnivore diet",
      "date": "October 31, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/patrick-heals-diabetes-ulcerative-colitis-carnivore-diet/",
      "title": "Patrick healed from Ulcerative Colitis on a carnivore diet",
      "date": "October 31, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/bruce-ileostomy-improved-ulcerative-colitis-carnivore-diet/",
      "title": "Bruce, despite ileostomy, improved ulcerative colitis on carnivore diet",
      "date": "October 11, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lee-improves-acid-reflux-and-digestion-on-a-carnivore-diet/",
      "title": "Lee improves acid reflux and digestion on a carnivore diet",
      "date": "April 26, 2024"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/francesco-manages-anger-and-depression-on-a-carnivore-lifestyle/",
      "title": "Francesco heals Ulcerative Colitis and depression on a carnivore lifestyle",
      "date": "November 24, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/jan-p-restored-her-gut-brain-chain-on-a-carnivore-lifestyle/",
      "title": "Jan P restored her \u2018gut-brain\u2019 chain on a Carnivore lifestyle",
      "date": "March 20, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/kelly-improved-kidney-disease-digestion-carnivore-diet/",
      "title": "Kelly improved her kidney disease on a carnivore diet",
      "date": "December 13, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/adam-treats-autoimmune-conditions-psoriasis-carnivore-diet/",
      "title": "Adam treats autoimmune conditions, joint pain, psoriasis on carnivore diet",
      "date": "October 31, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chris-improved-arthritis-tendinitis-carnivore-diet/",
      "title": "Chris improved arthritis, tendinitis, and lost weight on carnivore diet",
      "date": "March 21, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/edgar-improved-speech-carnivore-diet/",
      "title": "Edgar improved speech on a carnivore diet",
      "date": "November 1, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/daniel-improves-digestion-weight-loss-carnivore-diet/",
      "title": "Daniel improves his digestion and weight loss on a carnivore diet",
      "date": "October 5, 2018"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/lori-improved-hypertension-and-ulcerative-colitis-on-a-carnivore-diet/",
      "title": "Lori improved hypertension and ulcerative colitis on a carnivore diet",
      "date": "March 3, 2025"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/ramona-and-doug-improved-digestion-metabolic-markers-on-carnivore-diet/",
      "title": "Ramona and Doug improved digestion and metabolic markers on the carnivore diet",
      "date": "April 28, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chris-improved-diabetes-respiratory-issues-carnivore-diet/",
      "title": "Chris improved cardiovascular health, treated diabetes on carnivore diet",
      "date": "October 5, 2019"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/ulcerative-colitis/symptoms-causes/syc-20353326",
    "text": "Ulcerative colitis (UL-sur-uh-tiv koe-LIE-tis) is an inflammatory bowel disease (IBD) that causes inflammation and ulcers (sores) in your digestive tract. Ulcerative colitis affects the innermost lining of your large intestine, also called the colon, and rectum. In most people, symptoms usually develop over time, rather than suddenly."
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/rhinitis.json
{
  "visible": true,
  "name": "Rhinitis",
  "uri": "rhinitis",
  "carnivoreDietSearchQueries": [
    "Rhinitis"
  ],
  "filteredAnecdotes": [],
  "anecdotes": [
    {
      "visible": false,
      "uri": "https://carnivore.diet/martin-lost-anxiety-paranoia-fatigue-rhinitis-carnivore-diet/",
      "title": "Martin lost anxiety, paranoia, fatigue, rhinitis on carnivore diet",
      "date": "October 31, 2018"
    }
  ],
  "definition": {
    "source": "",
    "text": ""
  },
  "papers": [],
  "articles": [],
  "videos": []
}

=== codemonstur/site-plants-cause-disease/src/main/resources/disease/nafld.json
{
  "visible": true,
  "name": "NAFLD (Non-alcoholic Fatty Liver Disease)",
  "uri": "nafld",
  "carnivoreDietSearchQueries": [
    "Non-alcoholic Fatty Liver Disease",
    "NAFLD"
  ],
  "filteredAnecdotes": [
    "https://carnivore.diet/getting-hung-up-on-health-markers/",
    "https://carnivore.diet/coach-program/create-your-coaching-product/"
  ],
  "anecdotes": [
    {
      "visible": true,
      "uri": "https://carnivore.diet/eric-healed-non-alcoholic-fatty-liver-disease-migraines-arthritis-on-carnivore-lifestyle/",
      "title": "Eric healed non-alcoholic fatty liver disease, migraines, arthritis on carnivore lifestyle",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chandler-reversed-non-alcoholic-fatty-liver-gi-issues-and-inflammation-on-carnivore-diet/",
      "title": "Chandler reversed non-alcoholic fatty liver, GI issues, and inflammation on carnivore diet",
      "date": "March 22, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/cobus-improved-liver-weight-loss-nafld-carnivore-diet/",
      "title": "Cobus improved liver and weight loss, and treated NAFLD on carnivore diet",
      "date": "November 1, 2019"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/gregory-overcame-weight-lymphedema-high-blood-pressure-prediabetes-on-a-carnivore-diet/",
      "title": "Gregory overcame weight, lymphedema, high blood pressure, prediabetes on a carnivore diet",
      "date": "December 29, 2021"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/shawn-manages-obesity-diabetes-nafld-carnivore-diet/",
      "title": "Shawn W manages obesity, diabetes, NAFLD, hypertension, and depression on a carnivore diet",
      "date": "July 6, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/chana-heals-from-nafld-skin-issues-digestive-issues-and-pre-diabetes-on-a-carnivore-diet/",
      "title": "Chana Conquered NAFLD, Skin Issues, &amp; More on Carnivore Diet",
      "date": "January 10, 2023"
    },
    {
      "visible": true,
      "uri": "https://carnivore.diet/phillip-treated-allergies-respiratory-issues-carnivore-diet/",
      "title": "Phillip improved digestion, mood, mental health, and skin on carnivore diet",
      "date": "November 1, 2019"
    }
  ],
  "definition": {
    "source": "https://www.mayoclinic.org/diseases-conditions/nonalcoholic-fatty-liver-disease/symptoms-causes/syc-20354567",
    "text": "Nonalcoholic fatty liver disease, often called NAFLD, is a liver problem that affects people who drink little to no alcohol. In NAFLD, too much fat builds up in the liver. It is seen most often in people who are overweight or obese."
  },
  "papers": [],
  "articles": [],
  "videos": []
}
